### PR TITLE
add Markdown documentation to reference use cases

### PR DESCRIPTION
**Pull request by bernard357**
Are you ok with the format and content of the README.md provided with this use case? This would be reused for other use cases coming with this library. Waiting for your feed-back before engaging the work with other use cases.

### CODE REVIEW

**Comment by bernard357** [comment]
By the way: Let's Chat is similar to Slack. It can be connected to hubot as well, and so to Stackstorm...

**Comment by bernard357** [comment]
could not wait for feedback, so moved forward with additional documentation of container use cases...

**Comment by tonybaloney** [comment]
:+1: exactly what I meant

**Comment by bernard357** [comment]
ok great

**Pull request merged**
