### PR TITLE
deploy a mesosphere cluster

### PR DESCRIPTION
**Pull request by bernard357**
another stroke related to containers... here we want to be able to orchestrate a massive set of resources, ready for production, with 3 masters and 9 slaves

### CODE REVIEW

**Comment by tonybaloney** [comment]
nice! I was going to write this one next week but it looked pretty hard! thanks

**Comment by bernard357** [comment]
Travis CI build is failing because of the new version of the MCP API. Error message follows:

AttributeError: 'DimensionDataMockHttp' object has no attribute '_caas_2_2_8a8f6abc_2745_4d8a_9cbc_8dabe5a7d0e4_infrastructure_datacenter'

Anthony and team, how would you like to fix this please?

**Comment by bernard357** [comment]
This is it for this initial reference fittings plan on Mesosphere. This deploys a running cluster, and a job is submitted to Marathon to demonstrate the full thing. The PR wil be closed at this stage. Another PR can eventually be created to add full support of docker containers.

**Comment by bernard357** [comment]
This is it for this fittings plan. It provides a full Mesosphere cluster in less than 25 minutes, starting from scratch. Web interface is provided for Mesos and for Marathon, and a sample job is put in the cluster to demonstrates real work. Time for merging this PR please :-)

Full support of Docker can be added in a future version. Any brave here?

**Comment by bernard357** [comment]
@tonybaloney, you will be happy, since the reference Mesosphere fittings plan now fully supports Docker containers as well: [check updated doc page here](https://github.com/bernard357/plumbery-contrib/tree/master/fittings/containers/mesosphere-cluster). So, is this enough for you to either merge this PR, or to give me write access so that I can expedite it on your behalf? Thanks  :-)

**Pull request merged**
